import { Space_Mono } from 'next/font/google'
import './globals.css'
import 'react-toastify/dist/ReactToastify.css'
import { AuthProvider } from '@/contexts/Authcontext'
import { ToastContainer } from 'react-toastify'
import { Metadata } from 'next'

const space_mono = Space_Mono({ subsets: ['latin'], weight: '400' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br">
      <body className={space_mono.className}>
        <AuthProvider>{children}</AuthProvider>
        <ToastContainer autoClose={3000} />
      </body>
    </html>
  )
}
